version: "3.8"

services:
    web:
        build: .
        # Run with dev.py settings
        command: python manage.py runserver 0.0.0.0:8000 --settings=settings.dev
        container_name: web
        volumes:
            - .:/code
        ports:
            # Map port 8000 from CONTAINER to access at `localhost:8000`
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgis/postgis:12-3.0
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_USER=${NAME}
            - POSTGRES_DB=${DATABASE}

# Makes data persistent
volumes:
    postgres_data:
