# Generated by Django 2.0 on 2020-04-23 02:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20200422_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('4c67ab38-f4f4-4c61-bb4e-7293a43539da'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
