# Generated by Django 3.0.7 on 2020-06-19 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20200619_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('3c13c16b-0d24-41f0-9239-bf06712484bf'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
