# Generated by Django 2.0 on 2020-04-26 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20200422_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('04989ed3-a75b-4121-949a-cd4adf4338f8'), max_length=50, unique=True),
        ),
    ]
