# Generated by Django 3.0.7 on 2020-06-20 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_auto_20200619_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('874f1c08-992f-4107-8266-79d8064be9f7'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
