# Generated by Django 2.0 on 2020-04-26 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_auto_20200425_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('2f841f36-47fc-4d63-bf18-6b2f57e30b75'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
