# Generated by Django 2.0 on 2020-04-26 04:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_auto_20200425_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('62bf43f0-37d9-4a6d-990f-83e54cf5e299'), max_length=50, unique=True),
        ),
    ]
