# Generated by Django 3.0.7 on 2020-06-20 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_auto_20200620_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('72ea7a21-6e3a-4857-8a4b-df4cb5afb689'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
