# Generated by Django 2.0 on 2020-04-29 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20200425_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40, primary_key=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_logo',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('71585735-f99d-4793-9165-ada78fe2a48a'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
