# Generated by Django 3.0.7 on 2020-06-20 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20200620_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('b4a8a415-a295-445b-aa13-b02ee2f46a37'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
