# Generated by Django 2.0 on 2020-05-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_auto_20200429_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='id',
        ),
        migrations.AlterField(
            model_name='court',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='court',
            name='coordinates',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='court',
            name='road',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='court',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='court',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
