# Generated by Django 3.0.7 on 2020-06-20 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_auto_20200620_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='category',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Soccer', 'Soccer'), ('Tennis', 'Tennis')], default='Basketball', max_length=256),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('cf0ee762-c3fe-44a4-b2cd-4c2ffb096707'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
