# Generated by Django 2.0 on 2020-05-01 01:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_auto_20200430_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('38c12318-0f96-44c7-b893-61ccedf7227f'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
