# Generated by Django 2.0 on 2020-05-17 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0009_auto_20200430_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('2377f86c-9e03-434e-83e3-825d5f98c8f8'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
