# Generated by Django 2.0 on 2020-05-17 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0012_auto_20200517_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('27c36d93-47ca-4e58-b6bc-950cdf8c6ecc'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
