# Generated by Django 2.0 on 2020-05-17 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0013_auto_20200517_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.CharField(default=uuid.UUID('aa468983-8335-4f3f-9482-9764fdd8ed53'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
